import Utils from '../utils/common';

export default {
  accounts: [
    [
      2220107727,
      1,
      'savings',
      'active',
      0.00,
    ],
    [
      2220108726,
      3,
      'current',
      'dormant',
      0.00,
    ],
  ],
  users: [
    [
      'juwavictor@gmail.com',
      'Saladin',
      'Jake',
      Utils.hashPassword('password'),
      'staff',
      true,
    ],
    [
      'danielwollen@gmail.com',
      'Wallendorfer',
      'Daniel',
      Utils.hashPassword('password'),
      'staff',
      false,
    ],
    [
      'simba@gmail.com',
      'simba',
      'simba',
      Utils.hashPassword('password'),
      'client',
      false,
    ],
    [
      'test@gmail.com',
      'test',
      'test',
      Utils.hashPassword('password'),
      'client',
      false,
    ],
  ],
  transactions: [
    [
      2220107727,
      1,
      'debit',
      1000.00,
      0.00,
      1000.00,
      'danielwollen@gmail.com',
      'juwavictor@gmail.com'
    ],
    [
      2220107727,
      2,
      'debit',
      1000.00,
      0.00,
      10000.00,
      'danielwollen@gmail.com',
      'juwavictor@gmail.com'
    ],
    [
      2220107727,
      1,
      'debit',
      1000.00,
      0.00,
      10000.00,
      'simba@gmail.com',
      'juwavictor@gmail.com'
    ],
  ],
};
